/*global document*/

var myBackLis = document.getElementById('back-to-list'),
    myAudioSpace = document.getElementById('audio-space'),
    myLables = document.getElementById('lables'),
    myLable1 = document.getElementById('lable1'),
    myLable2 = document.getElementById('lable2'),
    myLable3 = document.getElementById('lable3'),
    myLable4 = document.getElementById('lable4'),
    myLable5 = document.getElementById('lable5'),
    myLable6 = document.getElementById('lable6'),
    myLable7 = document.getElementById('lable7'),
    myLable8 = document.getElementById('lable8'),
    myLable9 = document.getElementById('lable9'),
    myLable10 = document.getElementById('lable10'),
    myLable11 = document.getElementById('lable11'),
    myLable12 = document.getElementById('lable12'),
    myLable13 = document.getElementById('lable13'),
    myLable14 = document.getElementById('lable14'),
    myLable15 = document.getElementById('lable15'),
    myLable16 = document.getElementById('lable16'),
    myLable17 = document.getElementById('lable17'),
    myLable18 = document.getElementById('lable18'),
    myLable19 = document.getElementById('lable19'),
    myLable20 = document.getElementById('lable20'),
    myLable21 = document.getElementById('lable21'),
    myLable22 = document.getElementById('lable22'),
    myLable23 = document.getElementById('lable23'),
    myLable24 = document.getElementById('lable24'),
    myLable25 = document.getElementById('lable25'),
    myLable26 = document.getElementById('lable26'),
    myLable27 = document.getElementById('lable27'),
    myLable28 = document.getElementById('lable28'),
    myLable29 = document.getElementById('lable29'),
    myLable30 = document.getElementById('lable30'),
    myLable31 = document.getElementById('lable31'),
    myLable32 = document.getElementById('lable32'),
    myLable33 = document.getElementById('lable33'),
    myLable34 = document.getElementById('lable34'),
    myLable35 = document.getElementById('lable35'),
    myLable36 = document.getElementById('lable36'),
    myAudio1 = document.getElementById('audio1'),
    myAudio2 = document.getElementById('audio2'),
    myAudio3 = document.getElementById('audio3'),
    myAudio4 = document.getElementById('audio4'),
    myAudio5 = document.getElementById('audio5'),
    myAudio6 = document.getElementById('audio6'),
    myAudio7 = document.getElementById('audio7'),
    myAudio8 = document.getElementById('audio8'),
    myAudio9 = document.getElementById('audio9'),
    myAudio10 = document.getElementById('audio10'),
    myAudio11 = document.getElementById('audio11'),
    myAudio12 = document.getElementById('audio12'),
    myAudio13 = document.getElementById('audio13'),
    myAudio14 = document.getElementById('audio14'),
    myAudio15 = document.getElementById('audio15'),
    myAudio16 = document.getElementById('audio16'),
    myAudio17 = document.getElementById('audio17'),
    myAudio18 = document.getElementById('audio18'),
    myAudio19 = document.getElementById('audio19'),
    myAudio20 = document.getElementById('audio20'),
    myAudio21 = document.getElementById('audio21'),
    myAudio22 = document.getElementById('audio22'),
    myAudio23 = document.getElementById('audio23'),
    myAudio24 = document.getElementById('audio24'),
    myAudio25 = document.getElementById('audio25'),
    myAudio26 = document.getElementById('audio26'),
    myAudio27 = document.getElementById('audio27'),
    myAudio28 = document.getElementById('audio28'),
    myAudio29 = document.getElementById('audio29'),
    myAudio30 = document.getElementById('audio30'),
    myAudio31 = document.getElementById('audio31'),
    myAudio32 = document.getElementById('audio32'),
    myAudio33 = document.getElementById('audio33'),
    myAudio34 = document.getElementById('audio34'),
    myAudio35 = document.getElementById('audio35'),
    myAudio36 = document.getElementById('audio36'),
    myNounMusic = document.getElementById('music-noun'),
    myFront = document.getElementById('front'),
    myFrontBtn = document.getElementById('front-btn'),
    myBackHomeBtn = document.getElementById('back-home'),
    myAudio = document.getElementById('my-audio');

myFrontBtn.onclick = function () {
    'use strict';
    myFront.classList.add('hidden');
    myFront.classList.remove('show');
};

myBackHomeBtn.onclick = function () {
    'use strict';
    myFront.classList.remove('hidden');
    myFront.classList.add('show');
};

myLable1.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio1);
    myNounMusic.textContent = 'Avicii-The Nights';
    myLable1.classList.add('label-colour');
    myAudio1.classList.add('show');
    myAudio1.classList.remove('hidden');
    myAudio2.classList.add('hidden');
    myAudio2.classList.remove('show');
    myLable2.classList.remove('label-colour');
    myAudio3.classList.add('hidden');
    myAudio3.classList.remove('show');
    myLable3.classList.remove('label-colour');
    myAudio4.classList.add('hidden');
    myAudio4.classList.remove('show');
    myLable4.classList.remove('label-colour');
    myAudio5.classList.add('hidden');
    myAudio5.classList.remove('show');
    myLable5.classList.remove('label-colour');
    myAudio6.classList.add('hidden');
    myAudio6.classList.remove('show');
    myLable6.classList.remove('label-colour');
    myAudio7.classList.add('hidden');
    myAudio7.classList.remove('show');
    myLable7.classList.remove('label-colour');
    myAudio8.classList.add('hidden');
    myAudio8.classList.remove('show');
    myLable8.classList.remove('label-colour');
    myAudio9.classList.add('hidden');
    myAudio9.classList.remove('show');
    myLable9.classList.remove('label-colour');
    myAudio10.classList.add('hidden');
    myAudio10.classList.remove('show');
    myLable10.classList.remove('label-colour');
    myAudio11.classList.add('hidden');
    myAudio11.classList.remove('show');
    myLable11.classList.remove('label-colour');
    myAudio12.classList.add('hidden');
    myAudio12.classList.remove('show');
    myLable12.classList.remove('label-colour');
    myAudio13.classList.add('hidden');
    myAudio13.classList.remove('show');
    myLable13.classList.remove('label-colour');
    myAudio14.classList.add('hidden');
    myAudio14.classList.remove('show');
    myLable14.classList.remove('label-colour');
    myAudio15.classList.add('hidden');
    myAudio15.classList.remove('show');
    myLable15.classList.remove('label-colour');
    myAudio16.classList.add('hidden');
    myAudio16.classList.remove('hidden');
    myLable16.classList.remove('label-colour');
    myAudio17.classList.add('hidden');
    myAudio17.classList.remove('show');
    myLable17.classList.remove('label-colour');
    myAudio18.classList.add('hidden');
    myAudio18.classList.remove('show');
    myLable18.classList.remove('label-colour');
    myAudio19.classList.add('hidden');
    myAudio19.classList.remove('show');
    myLable19.classList.remove('label-colour');
    myAudio20.classList.add('hidden');
    myAudio20.classList.remove('show');
    myLable20.classList.remove('label-colour');
};

myLable2.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio2);
    myNounMusic.textContent = 'Billie Elish - Bad guy';
    myLable1.classList.remove('label-colour');
    myAudio1.classList.remove('show');
    myAudio1.classList.add('hidden');
    myAudio2.classList.add('show');
    myAudio2.classList.remove('hidden');
    myLable2.classList.add('label-colour');
    myAudio3.classList.add('hidden');
    myAudio3.classList.remove('show');
    myLable3.classList.remove('label-colour');
    myAudio4.classList.add('hidden');
    myAudio4.classList.remove('show');
    myLable4.classList.remove('label-colour');
    myAudio5.classList.add('hidden');
    myAudio5.classList.remove('show');
    myLable5.classList.remove('label-colour');
    myAudio6.classList.add('hidden');
    myAudio6.classList.remove('show');
    myLable6.classList.remove('label-colour');
    myAudio7.classList.add('hidden');
    myAudio7.classList.remove('show');
    myLable7.classList.remove('label-colour');
    myAudio8.classList.add('hidden');
    myAudio8.classList.remove('show');
    myLable8.classList.remove('label-colour');
    myAudio9.classList.add('hidden');
    myAudio9.classList.remove('show');
    myLable9.classList.remove('label-colour');
    myAudio10.classList.add('hidden');
    myAudio10.classList.remove('show');
    myLable10.classList.remove('label-colour');
    myAudio11.classList.add('hidden');
    myAudio11.classList.remove('show');
    myLable11.classList.remove('label-colour');
    myAudio12.classList.add('hidden');
    myAudio12.classList.remove('show');
    myLable12.classList.remove('label-colour');
    myAudio13.classList.add('hidden');
    myAudio13.classList.remove('show');
    myLable13.classList.remove('label-colour');
    myAudio14.classList.add('hidden');
    myAudio14.classList.remove('show');
    myLable14.classList.remove('label-colour');
    myAudio15.classList.add('hidden');
    myAudio15.classList.remove('show');
    myLable15.classList.remove('label-colour');
    myAudio16.classList.add('hidden');
    myAudio16.classList.remove('hidden');
    myLable16.classList.remove('label-colour');
    myAudio17.classList.add('hidden');
    myAudio17.classList.remove('show');
    myLable17.classList.remove('label-colour');
    myAudio18.classList.add('hidden');
    myAudio18.classList.remove('show');
    myLable18.classList.remove('label-colour');
    myAudio19.classList.add('hidden');
    myAudio19.classList.remove('show');
    myLable19.classList.remove('label-colour');
    myAudio20.classList.add('hidden');
    myAudio20.classList.remove('show');
    myLable20.classList.remove('label-colour');


};

myLable3.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio3);
    myNounMusic.textContent = 'Amr Diab We Malo عمرو دياب - وماله';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio2);
    myNounMusic.textContent = 'Billie Elish - Bad guy';
    myLable1.classList.remove('label-colour');
    myAudio1.classList.remove('show');
    myAudio1.classList.add('hidden');
    myAudio2.classList.add('hidden');
    myAudio2.classList.remove('show');
    myLable2.classList.remove('label-colour');
    myAudio3.classList.add('show');
    myAudio3.classList.remove('hidden');
    myLable3.classList.add('label-colour');
    myAudio4.classList.add('hidden');
    myAudio4.classList.remove('show');
    myLable4.classList.remove('label-colour');
    myAudio5.classList.add('hidden');
    myAudio5.classList.remove('show');
    myLable5.classList.remove('label-colour');
    myAudio6.classList.add('hidden');
    myAudio6.classList.remove('show');
    myLable6.classList.remove('label-colour');
    myAudio7.classList.add('hidden');
    myAudio7.classList.remove('show');
    myLable7.classList.remove('label-colour');
    myAudio8.classList.add('hidden');
    myAudio8.classList.remove('show');
    myLable8.classList.remove('label-colour');
    myAudio9.classList.add('hidden');
    myAudio9.classList.remove('show');
    myLable9.classList.remove('label-colour');
    myAudio10.classList.add('hidden');
    myAudio10.classList.remove('show');
    myLable10.classList.remove('label-colour');
    myAudio11.classList.add('hidden');
    myAudio11.classList.remove('show');
    myLable11.classList.remove('label-colour');
    myAudio12.classList.add('hidden');
    myAudio12.classList.remove('show');
    myLable12.classList.remove('label-colour');
    myAudio13.classList.add('hidden');
    myAudio13.classList.remove('show');
    myLable13.classList.remove('label-colour');
    myAudio14.classList.add('hidden');
    myAudio14.classList.remove('show');
    myLable14.classList.remove('label-colour');
    myAudio15.classList.add('hidden');
    myAudio15.classList.remove('show');
    myLable15.classList.remove('label-colour');
    myAudio16.classList.add('hidden');
    myAudio16.classList.remove('hidden');
    myLable16.classList.remove('label-colour');
    myAudio17.classList.add('hidden');
    myAudio17.classList.remove('show');
    myLable17.classList.remove('label-colour');
    myAudio18.classList.add('hidden');
    myAudio18.classList.remove('show');
    myLable18.classList.remove('label-colour');
    myAudio19.classList.add('hidden');
    myAudio19.classList.remove('show');
    myLable19.classList.remove('label-colour');
    myAudio20.classList.add('hidden');
    myAudio20.classList.remove('show');
    myLable20.classList.remove('label-colour');
};

myLable4.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio4);
    myNounMusic.textContent = 'Bad Bunny feat. Drake - Mia';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio2);
    myNounMusic.textContent = 'Billie Elish - Bad guy';
    myLable1.classList.remove('label-colour');
    myAudio1.classList.remove('show');
    myAudio1.classList.add('hidden');
    myAudio2.classList.add('hidden');
    myAudio2.classList.remove('show');
    myLable2.classList.remove('label-colour');
    myAudio3.classList.add('hidden');
    myAudio3.classList.remove('show');
    myLable3.classList.remove('label-colour');
    myAudio4.classList.add('show');
    myAudio4.classList.remove('hidden');
    myLable4.classList.add('label-colour');
    myAudio5.classList.add('hidden');
    myAudio5.classList.remove('show');
    myLable5.classList.remove('label-colour');
    myAudio6.classList.add('hidden');
    myAudio6.classList.remove('show');
    myLable6.classList.remove('label-colour');
    myAudio7.classList.add('hidden');
    myAudio7.classList.remove('show');
    myLable7.classList.remove('label-colour');
    myAudio8.classList.add('hidden');
    myAudio8.classList.remove('show');
    myLable8.classList.remove('label-colour');
    myAudio9.classList.add('hidden');
    myAudio9.classList.remove('show');
    myLable9.classList.remove('label-colour');
    myAudio10.classList.add('hidden');
    myAudio10.classList.remove('show');
    myLable10.classList.remove('label-colour');
    myAudio11.classList.add('hidden');
    myAudio11.classList.remove('show');
    myLable11.classList.remove('label-colour');
    myAudio12.classList.add('hidden');
    myAudio12.classList.remove('show');
    myLable12.classList.remove('label-colour');
    myAudio13.classList.add('hidden');
    myAudio13.classList.remove('show');
    myLable13.classList.remove('label-colour');
    myAudio14.classList.add('hidden');
    myAudio14.classList.remove('show');
    myLable14.classList.remove('label-colour');
    myAudio15.classList.add('hidden');
    myAudio15.classList.remove('show');
    myLable15.classList.remove('label-colour');
    myAudio16.classList.add('hidden');
    myAudio16.classList.remove('hidden');
    myLable16.classList.remove('label-colour');
    myAudio17.classList.add('hidden');
    myAudio17.classList.remove('show');
    myLable17.classList.remove('label-colour');
    myAudio18.classList.add('hidden');
    myAudio18.classList.remove('show');
    myLable18.classList.remove('label-colour');
    myAudio19.classList.add('hidden');
    myAudio19.classList.remove('show');
    myLable19.classList.remove('label-colour');
    myAudio20.classList.add('hidden');
    myAudio20.classList.remove('show');
    myLable20.classList.remove('label-colour');
};

myLable5.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio5);
    myNounMusic.textContent = 'Wait a Minute-Willow Smith';
    myLable1.classList.remove('label-colour');
    myAudio1.classList.remove('show');
    myAudio1.classList.add('hidden');
    myAudio2.classList.add('hidden');
    myAudio2.classList.remove('show');
    myLable2.classList.remove('label-colour');
    myAudio3.classList.add('hidden');
    myAudio3.classList.remove('show');
    myLable3.classList.remove('label-colour');
    myAudio4.classList.add('hidden');
    myAudio4.classList.remove('show');
    myLable4.classList.remove('label-colour');
    myAudio5.classList.add('show');
    myAudio5.classList.remove('hidden');
    myLable5.classList.add('label-colour');
    myAudio6.classList.add('hidden');
    myAudio6.classList.remove('show');
    myLable6.classList.remove('label-colour');
    myAudio7.classList.add('hidden');
    myAudio7.classList.remove('show');
    myLable7.classList.remove('label-colour');
    myAudio8.classList.add('hidden');
    myAudio8.classList.remove('show');
    myLable8.classList.remove('label-colour');
    myAudio9.classList.add('hidden');
    myAudio9.classList.remove('show');
    myLable9.classList.remove('label-colour');
    myAudio10.classList.add('hidden');
    myAudio10.classList.remove('show');
    myLable10.classList.remove('label-colour');
    myAudio11.classList.add('hidden');
    myAudio11.classList.remove('show');
    myLable11.classList.remove('label-colour');
    myAudio12.classList.add('hidden');
    myAudio12.classList.remove('show');
    myLable12.classList.remove('label-colour');
    myAudio13.classList.add('hidden');
    myAudio13.classList.remove('show');
    myLable13.classList.remove('label-colour');
    myAudio14.classList.add('hidden');
    myAudio14.classList.remove('show');
    myLable14.classList.remove('label-colour');
    myAudio15.classList.add('hidden');
    myAudio15.classList.remove('show');
    myLable15.classList.remove('label-colour');
    myAudio16.classList.add('hidden');
    myAudio16.classList.remove('hidden');
    myLable16.classList.remove('label-colour');
    myAudio17.classList.add('hidden');
    myAudio17.classList.remove('show');
    myLable17.classList.remove('label-colour');
    myAudio18.classList.add('hidden');
    myAudio18.classList.remove('show');
    myLable18.classList.remove('label-colour');
    myAudio19.classList.add('hidden');
    myAudio19.classList.remove('show');
    myLable19.classList.remove('label-colour');
    myAudio20.classList.add('hidden');
    myAudio20.classList.remove('show');
    myLable20.classList.remove('label-colour');
};

myLable6.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio6);
    myNounMusic.textContent = 'Abdulrahman | Craziness';
    myLable1.classList.remove('label-colour');
    myAudio1.classList.remove('show');
    myAudio1.classList.add('hidden');
    myAudio2.classList.add('hidden');
    myAudio2.classList.remove('show');
    myLable2.classList.remove('label-colour');
    myAudio3.classList.add('hidden');
    myAudio3.classList.remove('show');
    myLable3.classList.remove('label-colour');
    myAudio4.classList.add('hidden');
    myAudio4.classList.remove('show');
    myLable4.classList.remove('label-colour');
    myAudio5.classList.add('hiiden');
    myAudio5.classList.remove('show');
    myLable5.classList.remove('label-colour');
    myAudio6.classList.add('show');
    myAudio6.classList.remove('hidden');
    myLable6.classList.add('label-colour');
    myAudio7.classList.add('hidden');
    myAudio7.classList.remove('show');
    myLable7.classList.remove('label-colour');
    myAudio8.classList.add('hidden');
    myAudio8.classList.remove('show');
    myLable8.classList.remove('label-colour');
    myAudio9.classList.add('hidden');
    myAudio9.classList.remove('show');
    myLable9.classList.remove('label-colour');
    myAudio10.classList.add('hidden');
    myAudio10.classList.remove('show');
    myLable10.classList.remove('label-colour');
    myAudio11.classList.add('hidden');
    myAudio11.classList.remove('show');
    myLable11.classList.remove('label-colour');
    myAudio12.classList.add('hidden');
    myAudio12.classList.remove('show');
    myLable12.classList.remove('label-colour');
    myAudio13.classList.add('hidden');
    myAudio13.classList.remove('show');
    myLable13.classList.remove('label-colour');
    myAudio14.classList.add('hidden');
    myAudio14.classList.remove('show');
    myLable14.classList.remove('label-colour');
    myAudio15.classList.add('hidden');
    myAudio15.classList.remove('show');
    myLable15.classList.remove('label-colour');
    myAudio16.classList.add('hidden');
    myAudio16.classList.remove('hidden');
    myLable16.classList.remove('label-colour');
    myAudio17.classList.add('hidden');
    myAudio17.classList.remove('show');
    myLable17.classList.remove('label-colour');
    myAudio18.classList.add('hidden');
    myAudio18.classList.remove('show');
    myLable18.classList.remove('label-colour');
    myAudio19.classList.add('hidden');
    myAudio19.classList.remove('show');
    myLable19.classList.remove('label-colour');
    myAudio20.classList.add('hidden');
    myAudio20.classList.remove('show');
    myLable20.classList.remove('label-colour');
};

myLable7.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio7);
    myNounMusic.textContent = 'Becky G Ft. Maluma – La Respuesta';
    myAudio1.classList.remove('show');
    myAudio1.classList.add('hidden');
    myLable1.classList.remove('label-colour');
    myAudio2.classList.add('hidden');
    myAudio2.classList.remove('show');
    myLable2.classList.remove('label-colour');
    myAudio3.classList.add('hidden');
    myAudio3.classList.remove('show');
    myLable3.classList.remove('label-colour');
    myAudio4.classList.add('hidden');
    myAudio4.classList.remove('show');
    myLable4.classList.remove('label-colour');
    myAudio5.classList.add('hiiden');
    myAudio5.classList.remove('show');
    myLable5.classList.remove('label-colour');
    myAudio6.classList.add('hidden');
    myAudio6.classList.remove('show');
    myLable6.classList.remove('label-colour');
    myAudio7.classList.add('show');
    myAudio7.classList.remove('hidden');
    myLable7.classList.add('label-colour');
    myAudio8.classList.add('hidden');
    myAudio8.classList.remove('show');
    myLable8.classList.remove('label-colour');
    myAudio9.classList.add('hidden');
    myAudio9.classList.remove('show');
    myLable9.classList.remove('label-colour');
    myAudio10.classList.add('hidden');
    myAudio10.classList.remove('show');
    myLable10.classList.remove('label-colour');
    myAudio11.classList.add('hidden');
    myAudio11.classList.remove('show');
    myLable11.classList.remove('label-colour');
    myAudio12.classList.add('hidden');
    myAudio12.classList.remove('show');
    myLable12.classList.remove('label-colour');
    myAudio13.classList.add('hidden');
    myAudio13.classList.remove('show');
    myLable13.classList.remove('label-colour');
    myAudio14.classList.add('hidden');
    myAudio14.classList.remove('show');
    myLable14.classList.remove('label-colour');
    myAudio15.classList.add('hidden');
    myAudio15.classList.remove('show');
    myLable15.classList.remove('label-colour');
    myAudio16.classList.add('hidden');
    myAudio16.classList.remove('hidden');
    myLable16.classList.remove('label-colour');
    myAudio17.classList.add('hidden');
    myAudio17.classList.remove('show');
    myLable17.classList.remove('label-colour');
    myAudio18.classList.add('hidden');
    myAudio18.classList.remove('show');
    myLable18.classList.remove('label-colour');
    myAudio19.classList.add('hidden');
    myAudio19.classList.remove('show');
    myLable19.classList.remove('label-colour');
    myAudio20.classList.add('hidden');
    myAudio20.classList.remove('show');
    myLable20.classList.remove('label-colour');

};

myLable8.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio8);
    myNounMusic.textContent = 'Selena Gomez_ J Balvin - I Can\'t get It Enough';
    myAudio1.classList.remove('show');
    myAudio1.classList.add('hidden');
    myLable1.classList.remove('label-colour');
    myAudio2.classList.add('hidden');
    myAudio2.classList.remove('show');
    myLable2.classList.remove('label-colour');
    myAudio3.classList.add('hidden');
    myAudio3.classList.remove('show');
    myLable3.classList.remove('label-colour');
    myAudio4.classList.add('hidden');
    myAudio4.classList.remove('show');
    myLable4.classList.remove('label-colour');
    myAudio5.classList.add('hiiden');
    myAudio5.classList.remove('show');
    myLable5.classList.remove('label-colour');
    myAudio6.classList.add('hidden');
    myAudio6.classList.remove('show');
    myLable6.classList.remove('label-colour');
    myAudio7.classList.add('hidden');
    myAudio7.classList.remove('show');
    myLable7.classList.remove('label-colour');
    myAudio8.classList.remove('hidden');
    myAudio8.classList.add('show');
    myLable8.classList.add('label-colour');
    myAudio9.classList.add('hidden');
    myAudio9.classList.remove('show');
    myLable9.classList.remove('label-colour');
    myAudio10.classList.add('hidden');
    myAudio10.classList.remove('show');
    myLable10.classList.remove('label-colour');
    myAudio11.classList.add('hidden');
    myAudio11.classList.remove('show');
    myLable11.classList.remove('label-colour');
    myAudio12.classList.add('hidden');
    myAudio12.classList.remove('show');
    myLable12.classList.remove('label-colour');
    myAudio13.classList.add('hidden');
    myAudio13.classList.remove('show');
    myLable13.classList.remove('label-colour');
    myAudio14.classList.add('hidden');
    myAudio14.classList.remove('show');
    myLable14.classList.remove('label-colour');
    myAudio15.classList.add('hidden');
    myAudio15.classList.remove('show');
    myLable15.classList.remove('label-colour');
    myAudio16.classList.add('hidden');
    myAudio16.classList.remove('hidden');
    myLable16.classList.remove('label-colour');
    myAudio17.classList.add('hidden');
    myAudio17.classList.remove('show');
    myLable17.classList.remove('label-colour');
    myAudio18.classList.add('hidden');
    myAudio18.classList.remove('show');
    myLable18.classList.remove('label-colour');
    myAudio19.classList.add('hidden');
    myAudio19.classList.remove('show');
    myLable19.classList.remove('label-colour');
    myAudio20.classList.add('hidden');
    myAudio20.classList.remove('show');
    myLable20.classList.remove('label-colour');
};

myLable9.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio9);
    myNounMusic.textContent = 'Billie Eilish - i love you';
    myAudio1.classList.remove('show');
    myAudio1.classList.add('hidden');
    myLable1.classList.remove('label-colour');
    myAudio2.classList.add('hidden');
    myAudio2.classList.remove('show');
    myLable2.classList.remove('label-colour');
    myAudio3.classList.add('hidden');
    myAudio3.classList.remove('show');
    myLable3.classList.remove('label-colour');
    myAudio4.classList.add('hidden');
    myAudio4.classList.remove('show');
    myLable4.classList.remove('label-colour');
    myAudio5.classList.add('hiiden');
    myAudio5.classList.remove('show');
    myLable5.classList.remove('label-colour');
    myAudio6.classList.add('hidden');
    myAudio6.classList.remove('show');
    myLable6.classList.remove('label-colour');
    myAudio7.classList.add('hidden');
    myAudio7.classList.remove('show');
    myLable7.classList.remove('label-colour');
    myAudio8.classList.add('hidden');
    myAudio8.classList.remove('show');
    myLable8.classList.remove('label-colour');
    myAudio9.classList.add('show');
    myAudio9.classList.remove('hidden');
    myLable9.classList.add('label-colour');
    myAudio10.classList.add('hidden');
    myAudio10.classList.remove('show');
    myLable10.classList.remove('label-colour');
    myAudio11.classList.add('hidden');
    myAudio11.classList.remove('show');
    myLable11.classList.remove('label-colour');
    myAudio12.classList.add('hidden');
    myAudio12.classList.remove('show');
    myLable12.classList.remove('label-colour');
    myAudio13.classList.add('hidden');
    myAudio13.classList.remove('show');
    myLable13.classList.remove('label-colour');
    myAudio14.classList.add('hidden');
    myAudio14.classList.remove('show');
    myLable14.classList.remove('label-colour');
    myAudio15.classList.add('hidden');
    myAudio15.classList.remove('show');
    myLable15.classList.remove('label-colour');
    myAudio16.classList.add('hidden');
    myAudio16.classList.remove('hidden');
    myLable16.classList.remove('label-colour');
    myAudio17.classList.add('hidden');
    myAudio17.classList.remove('show');
    myLable17.classList.remove('label-colour');
    myAudio18.classList.add('hidden');
    myAudio18.classList.remove('show');
    myLable18.classList.remove('label-colour');
    myAudio19.classList.add('hidden');
    myAudio19.classList.remove('show');
    myLable19.classList.remove('label-colour');
    myAudio20.classList.add('hidden');
    myAudio20.classList.remove('show');
    myLable20.classList.remove('label-colour');
};

myLable10.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio10);
    myNounMusic.textContent = 'Billie Eilish - lovely ft. Khalid';
    myAudio1.classList.remove('show');
    myAudio1.classList.add('hidden');
    myLable1.classList.remove('label-colour');
    myAudio2.classList.add('hidden');
    myAudio2.classList.remove('show');
    myLable2.classList.remove('label-colour');
    myAudio3.classList.add('hidden');
    myAudio3.classList.remove('show');
    myLable3.classList.remove('label-colour');
    myAudio4.classList.add('hidden');
    myAudio4.classList.remove('show');
    myLable4.classList.remove('label-colour');
    myAudio5.classList.add('hiiden');
    myAudio5.classList.remove('show');
    myLable5.classList.remove('label-colour');
    myAudio6.classList.add('hidden');
    myAudio6.classList.remove('show');
    myLable6.classList.remove('label-colour');
    myAudio7.classList.add('hidden');
    myAudio7.classList.remove('show');
    myLable7.classList.remove('label-colour');
    myAudio8.classList.add('hidden');
    myAudio8.classList.remove('show');
    myLable8.classList.remove('label-colour');
    myAudio9.classList.add('hidden');
    myAudio9.classList.remove('show');
    myLable9.classList.remove('label-colour');
    myAudio10.classList.add('show');
    myAudio10.classList.remove('hidden');
    myLable10.classList.add('label-colour');
    myAudio11.classList.add('hidden');
    myAudio11.classList.remove('show');
    myLable11.classList.remove('label-colour');
    myAudio12.classList.add('hidden');
    myAudio12.classList.remove('show');
    myLable12.classList.remove('label-colour');
    myAudio13.classList.add('hidden');
    myAudio13.classList.remove('show');
    myLable13.classList.remove('label-colour');
    myAudio14.classList.add('hidden');
    myAudio14.classList.remove('show');
    myLable14.classList.remove('label-colour');
    myAudio15.classList.add('hidden');
    myAudio15.classList.remove('show');
    myLable15.classList.remove('label-colour');
    myAudio16.classList.add('hidden');
    myAudio16.classList.remove('hidden');
    myLable16.classList.remove('label-colour');
    myAudio17.classList.add('hidden');
    myAudio17.classList.remove('show');
    myLable17.classList.remove('label-colour');
    myAudio18.classList.add('hidden');
    myAudio18.classList.remove('show');
    myLable18.classList.remove('label-colour');
    myAudio19.classList.add('hidden');
    myAudio19.classList.remove('show');
    myLable19.classList.remove('label-colour');
    myAudio20.classList.add('hidden');
    myAudio20.classList.remove('show');
    myLable20.classList.remove('label-colour');
};

myLable11.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio11);
    myNounMusic.textContent = 'Bratia Stereo _ Ayayay ft.Tony Tonite';
    myAudio1.classList.remove('show');
    myAudio1.classList.add('hidden');
    myLable1.classList.remove('label-colour');
    myAudio2.classList.add('hidden');
    myAudio2.classList.remove('show');
    myLable2.classList.remove('label-colour');
    myAudio3.classList.add('hidden');
    myAudio3.classList.remove('show');
    myLable3.classList.remove('label-colour');
    myAudio4.classList.add('hidden');
    myAudio4.classList.remove('show');
    myLable4.classList.remove('label-colour');
    myAudio5.classList.add('hiiden');
    myAudio5.classList.remove('show');
    myLable5.classList.remove('label-colour');
    myAudio6.classList.add('hidden');
    myAudio6.classList.remove('show');
    myLable6.classList.remove('label-colour');
    myAudio7.classList.add('hidden');
    myAudio7.classList.remove('show');
    myLable7.classList.remove('label-colour');
    myAudio8.classList.add('hidden');
    myAudio8.classList.remove('show');
    myLable8.classList.remove('label-colour');
    myAudio9.classList.add('hidden');
    myAudio9.classList.remove('show');
    myLable9.classList.remove('label-colour');
    myAudio10.classList.add('hidden');
    myAudio10.classList.remove('show');
    myLable10.classList.remove('label-colour');
    myAudio11.classList.add('show');
    myAudio11.classList.remove('hidden');
    myLable11.classList.add('label-colour');
    myAudio12.classList.add('hidden');
    myAudio12.classList.remove('show');
    myLable12.classList.remove('label-colour');
    myAudio13.classList.add('hidden');
    myAudio13.classList.remove('show');
    myLable13.classList.remove('label-colour');
    myAudio14.classList.add('hidden');
    myAudio14.classList.remove('show');
    myLable14.classList.remove('label-colour');
    myAudio15.classList.add('hidden');
    myAudio15.classList.remove('show');
    myLable15.classList.remove('label-colour');
    myAudio16.classList.add('hidden');
    myAudio16.classList.remove('hidden');
    myLable16.classList.remove('label-colour');
    myAudio17.classList.add('hidden');
    myAudio17.classList.remove('show');
    myLable17.classList.remove('label-colour');
    myAudio18.classList.add('hidden');
    myAudio18.classList.remove('show');
    myLable18.classList.remove('label-colour');
    myAudio19.classList.add('hidden');
    myAudio19.classList.remove('show');
    myLable19.classList.remove('label-colour');
    myAudio20.classList.add('hidden');
    myAudio20.classList.remove('show');
    myLable20.classList.remove('label-colour');
};

myLable12.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio12);
    myNounMusic.textContent = 'Carole Samaha - Khallik Behalak';
    myAudio1.classList.remove('show');
    myAudio1.classList.add('hidden');
    myLable1.classList.remove('label-colour');
    myAudio2.classList.add('hidden');
    myAudio2.classList.remove('show');
    myLable2.classList.remove('label-colour');
    myAudio3.classList.add('hidden');
    myAudio3.classList.remove('show');
    myLable3.classList.remove('label-colour');
    myAudio4.classList.add('hidden');
    myAudio4.classList.remove('show');
    myLable4.classList.remove('label-colour');
    myAudio5.classList.add('hiiden');
    myAudio5.classList.remove('show');
    myLable5.classList.remove('label-colour');
    myAudio6.classList.add('hidden');
    myAudio6.classList.remove('show');
    myLable6.classList.remove('label-colour');
    myAudio7.classList.add('hidden');
    myAudio7.classList.remove('show');
    myLable7.classList.remove('label-colour');
    myAudio8.classList.add('hidden');
    myAudio8.classList.remove('show');
    myLable8.classList.remove('label-colour');
    myAudio9.classList.add('hidden');
    myAudio9.classList.remove('show');
    myLable9.classList.remove('label-colour');
    myAudio10.classList.add('hidden');
    myAudio10.classList.remove('show');
    myLable10.classList.remove('label-colour');
    myAudio11.classList.add('hidden');
    myAudio11.classList.remove('show');
    myLable11.classList.remove('label-colour');
    myAudio12.classList.add('show');
    myAudio12.classList.remove('hidden');
    myLable12.classList.add('label-colour');
    myAudio13.classList.add('hidden');
    myAudio13.classList.remove('show');
    myLable13.classList.remove('label-colour');
    myAudio14.classList.add('hidden');
    myAudio14.classList.remove('show');
    myLable14.classList.remove('label-colour');
    myAudio15.classList.add('hidden');
    myAudio15.classList.remove('show');
    myLable15.classList.remove('label-colour');
    myAudio16.classList.add('hidden');
    myAudio16.classList.remove('hidden');
    myLable16.classList.remove('label-colour');
    myAudio17.classList.add('hidden');
    myAudio17.classList.remove('show');
    myLable17.classList.remove('label-colour');
    myAudio18.classList.add('hidden');
    myAudio18.classList.remove('show');
    myLable18.classList.remove('label-colour');
    myAudio19.classList.add('hidden');
    myAudio19.classList.remove('show');
    myLable19.classList.remove('label-colour');
    myAudio20.classList.add('hidden');
    myAudio20.classList.remove('show');
    myLable20.classList.remove('label-colour');
};

myLable13.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio13);
    myNounMusic.textContent = 'Catey Shaw - Night Go Slow';
    myAudio1.classList.remove('show');
    myAudio1.classList.add('hidden');
    myLable1.classList.remove('label-colour');
    myAudio2.classList.add('hidden');
    myAudio2.classList.remove('show');
    myLable2.classList.remove('label-colour');
    myAudio3.classList.add('hidden');
    myAudio3.classList.remove('show');
    myLable3.classList.remove('label-colour');
    myAudio4.classList.add('hidden');
    myAudio4.classList.remove('show');
    myLable4.classList.remove('label-colour');
    myAudio5.classList.add('hiiden');
    myAudio5.classList.remove('show');
    myLable5.classList.remove('label-colour');
    myAudio6.classList.add('hidden');
    myAudio6.classList.remove('show');
    myLable6.classList.remove('label-colour');
    myAudio7.classList.add('hidden');
    myAudio7.classList.remove('show');
    myLable7.classList.remove('label-colour');
    myAudio8.classList.add('hidden');
    myAudio8.classList.remove('show');
    myLable8.classList.remove('label-colour');
    myAudio9.classList.add('hidden');
    myAudio9.classList.remove('show');
    myLable9.classList.remove('label-colour');
    myAudio10.classList.add('hidden');
    myAudio10.classList.remove('show');
    myLable10.classList.remove('label-colour');
    myAudio11.classList.add('hidden');
    myAudio11.classList.remove('show');
    myLable11.classList.remove('label-colour');
    myAudio12.classList.add('hidden');
    myAudio12.classList.remove('show');
    myLable12.classList.remove('label-colour');
    myAudio13.classList.add('show');
    myAudio13.classList.remove('hidden');
    myLable13.classList.add('label-colour');
    myAudio14.classList.add('hidden');
    myAudio14.classList.remove('show');
    myLable14.classList.remove('label-colour');
    myAudio15.classList.add('hidden');
    myAudio15.classList.remove('show');
    myLable15.classList.remove('label-colour');
    myAudio16.classList.add('hidden');
    myAudio16.classList.remove('hidden');
    myLable16.classList.remove('label-colour');
    myAudio17.classList.add('hidden');
    myAudio17.classList.remove('show');
    myLable17.classList.remove('label-colour');
    myAudio18.classList.add('hidden');
    myAudio18.classList.remove('show');
    myLable18.classList.remove('label-colour');
    myAudio19.classList.add('hidden');
    myAudio19.classList.remove('show');
    myLable19.classList.remove('label-colour');
    myAudio20.classList.add('hidden');
    myAudio20.classList.remove('show');
    myLable20.classList.remove('label-colour');
};

myLable14.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio14);
    myNounMusic.textContent = 'Catey Shaw - Walks All Over You';
    myAudio1.classList.remove('show');
    myAudio1.classList.add('hidden');
    myLable1.classList.remove('label-colour');
    myAudio2.classList.add('hidden');
    myAudio2.classList.remove('show');
    myLable2.classList.remove('label-colour');
    myAudio3.classList.add('hidden');
    myAudio3.classList.remove('show');
    myLable3.classList.remove('label-colour');
    myAudio4.classList.add('hidden');
    myAudio4.classList.remove('show');
    myLable4.classList.remove('label-colour');
    myAudio5.classList.add('hiiden');
    myAudio5.classList.remove('show');
    myLable5.classList.remove('label-colour');
    myAudio6.classList.add('hidden');
    myAudio6.classList.remove('show');
    myLable6.classList.remove('label-colour');
    myAudio7.classList.add('hidden');
    myAudio7.classList.remove('show');
    myLable7.classList.remove('label-colour');
    myAudio8.classList.add('hidden');
    myAudio8.classList.remove('show');
    myLable8.classList.remove('label-colour');
    myAudio9.classList.add('hidden');
    myAudio9.classList.remove('show');
    myLable9.classList.remove('label-colour');
    myAudio10.classList.add('hidden');
    myAudio10.classList.remove('show');
    myLable10.classList.remove('label-colour');
    myAudio11.classList.add('hidden');
    myAudio11.classList.remove('show');
    myLable11.classList.remove('label-colour');
    myAudio12.classList.add('hidden');
    myAudio12.classList.remove('show');
    myLable12.classList.remove('label-colour');
    myAudio13.classList.add('hidden');
    myAudio13.classList.remove('show');
    myLable13.classList.remove('label-colour');
    myAudio14.classList.add('show');
    myAudio14.classList.remove('hidden');
    myLable14.classList.add('label-colour');
    myAudio15.classList.add('hidden');
    myAudio15.classList.remove('show');
    myLable15.classList.remove('label-colour');
    myAudio16.classList.add('hidden');
    myAudio16.classList.remove('hidden');
    myLable16.classList.remove('label-colour');
    myAudio17.classList.add('hidden');
    myAudio17.classList.remove('show');
    myLable17.classList.remove('label-colour');
    myAudio18.classList.add('hidden');
    myAudio18.classList.remove('show');
    myLable18.classList.remove('label-colour');
    myAudio19.classList.add('hidden');
    myAudio19.classList.remove('show');
    myLable19.classList.remove('label-colour');
    myAudio20.classList.add('hidden');
    myAudio20.classList.remove('show');
    myLable20.classList.remove('label-colour');
};

myLable15.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio15);
    myNounMusic.textContent = 'GIMS_ Maluma - Hola Señorita';
    myAudio1.classList.remove('show');
    myAudio1.classList.add('hidden');
    myLable1.classList.remove('label-colour');
    myAudio2.classList.add('hidden');
    myAudio2.classList.remove('show');
    myLable2.classList.remove('label-colour');
    myAudio3.classList.add('hidden');
    myAudio3.classList.remove('show');
    myLable3.classList.remove('label-colour');
    myAudio4.classList.add('hidden');
    myAudio4.classList.remove('show');
    myLable4.classList.remove('label-colour');
    myAudio5.classList.add('hiiden');
    myAudio5.classList.remove('show');
    myLable5.classList.remove('label-colour');
    myAudio6.classList.add('hidden');
    myAudio6.classList.remove('show');
    myLable6.classList.remove('label-colour');
    myAudio7.classList.add('hidden');
    myAudio7.classList.remove('show');
    myLable7.classList.remove('label-colour');
    myAudio8.classList.add('hidden');
    myAudio8.classList.remove('show');
    myLable8.classList.remove('label-colour');
    myAudio9.classList.add('hidden');
    myAudio9.classList.remove('show');
    myLable9.classList.remove('label-colour');
    myAudio10.classList.add('hidden');
    myAudio10.classList.remove('show');
    myLable10.classList.remove('label-colour');
    myAudio11.classList.add('hidden');
    myAudio11.classList.remove('show');
    myLable11.classList.remove('label-colour');
    myAudio12.classList.add('hidden');
    myAudio12.classList.remove('show');
    myLable12.classList.remove('label-colour');
    myAudio13.classList.add('hidden');
    myAudio13.classList.remove('show');
    myLable13.classList.remove('label-colour');
    myAudio14.classList.add('hidden');
    myAudio14.classList.remove('show');
    myLable14.classList.remove('label-colour');
    myAudio15.classList.add('show');
    myAudio15.classList.remove('hidden');
    myLable15.classList.add('label-colour');
    myAudio16.classList.add('hidden');
    myAudio16.classList.remove('hidden');
    myLable16.classList.remove('label-colour');
    myAudio17.classList.add('hidden');
    myAudio17.classList.remove('show');
    myLable17.classList.remove('label-colour');
    myAudio18.classList.add('hidden');
    myAudio18.classList.remove('show');
    myLable18.classList.remove('label-colour');
    myAudio19.classList.add('hidden');
    myAudio19.classList.remove('show');
    myLable19.classList.remove('label-colour');
    myAudio20.classList.add('hidden');
    myAudio20.classList.remove('show');
    myLable20.classList.remove('label-colour');
};

myLable16.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio16);
    myNounMusic.textContent = 'Glimmer of Blooms-Get You Out Of My Head';
    myAudio1.classList.remove('show');
    myAudio1.classList.add('hidden');
    myLable1.classList.remove('label-colour');
    myAudio2.classList.add('hidden');
    myAudio2.classList.remove('show');
    myLable2.classList.remove('label-colour');
    myAudio3.classList.add('hidden');
    myAudio3.classList.remove('show');
    myLable3.classList.remove('label-colour');
    myAudio4.classList.add('hidden');
    myAudio4.classList.remove('show');
    myLable4.classList.remove('label-colour');
    myAudio5.classList.add('hiiden');
    myAudio5.classList.remove('show');
    myLable5.classList.remove('label-colour');
    myAudio6.classList.add('hidden');
    myAudio6.classList.remove('show');
    myLable6.classList.remove('label-colour');
    myAudio7.classList.add('hidden');
    myAudio7.classList.remove('show');
    myLable7.classList.remove('label-colour');
    myAudio8.classList.add('hidden');
    myAudio8.classList.remove('show');
    myLable8.classList.remove('label-colour');
    myAudio9.classList.add('hidden');
    myAudio9.classList.remove('show');
    myLable9.classList.remove('label-colour');
    myAudio10.classList.add('hidden');
    myAudio10.classList.remove('show');
    myLable10.classList.remove('label-colour');
    myAudio11.classList.add('hidden');
    myAudio11.classList.remove('show');
    myLable11.classList.remove('label-colour');
    myAudio12.classList.add('hidden');
    myAudio12.classList.remove('show');
    myLable12.classList.remove('label-colour');
    myAudio13.classList.add('hidden');
    myAudio13.classList.remove('show');
    myLable13.classList.remove('label-colour');
    myAudio14.classList.add('hidden');
    myAudio14.classList.remove('show');
    myLable14.classList.remove('label-colour');
    myAudio15.classList.add('hidden');
    myAudio15.classList.remove('show');
    myLable15.classList.remove('label-colour');
    myAudio16.classList.add('show');
    myAudio16.classList.remove('hidden');
    myLable16.classList.add('label-colour');
    myAudio17.classList.add('hidden');
    myAudio17.classList.remove('show');
    myLable17.classList.remove('label-colour');
    myAudio18.classList.add('hidden');
    myAudio18.classList.remove('show');
    myLable18.classList.remove('label-colour');
    myAudio19.classList.add('hidden');
    myAudio19.classList.remove('show');
    myLable19.classList.remove('label-colour');
    myAudio20.classList.add('hidden');
    myAudio20.classList.remove('show');
    myLable20.classList.remove('label-colour');
};

myLable17.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio17);
    myNounMusic.textContent = 'Kendji Girac - Tiago';
    myAudio1.classList.remove('show');
    myAudio1.classList.add('hidden');
    myLable1.classList.remove('label-colour');
    myAudio2.classList.add('hidden');
    myAudio2.classList.remove('show');
    myAudio2.classList.add('hidden');
    myLable2.classList.remove('label-colour');
    myAudio3.classList.remove('show');
    myLable3.classList.remove('label-colour');
    myAudio4.classList.add('hidden');
    myAudio4.classList.remove('show');
    myLable4.classList.remove('label-colour');
    myAudio5.classList.add('hiiden');
    myAudio5.classList.remove('show');
    myLable5.classList.remove('label-colour');
    myAudio6.classList.add('hidden');
    myAudio6.classList.remove('show');
    myLable6.classList.remove('label-colour');
    myAudio7.classList.add('hidden');
    myAudio7.classList.remove('show');
    myLable7.classList.remove('label-colour');
    myAudio8.classList.add('hidden');
    myAudio8.classList.remove('show');
    myLable8.classList.remove('label-colour');
    myAudio9.classList.add('hidden');
    myAudio9.classList.remove('show');
    myLable9.classList.remove('label-colour');
    myAudio10.classList.add('hidden');
    myAudio10.classList.remove('show');
    myLable10.classList.remove('label-colour');
    myAudio11.classList.add('hidden');
    myAudio11.classList.remove('show');
    myLable11.classList.remove('label-colour');
    myAudio12.classList.add('hidden');
    myAudio12.classList.remove('show');
    myLable12.classList.remove('label-colour');
    myAudio13.classList.add('hidden');
    myAudio13.classList.remove('show');
    myLable13.classList.remove('label-colour');
    myAudio14.classList.add('hidden');
    myAudio14.classList.remove('show');
    myLable14.classList.remove('label-colour');
    myAudio15.classList.add('hidden');
    myAudio15.classList.remove('show');
    myLable15.classList.remove('label-colour');
    myAudio16.classList.add('hidden');
    myAudio16.classList.remove('show');
    myLable16.classList.remove('label-colour');
    myAudio17.classList.add('show');
    myAudio17.classList.remove('hidden');
    myLable17.classList.add('label-colour');
    myAudio18.classList.add('hidden');
    myAudio18.classList.remove('show');
    myLable18.classList.remove('label-colour');
    myAudio19.classList.add('hidden');
    myAudio19.classList.remove('show');
    myLable19.classList.remove('label-colour');
    myAudio20.classList.add('hidden');
    myAudio20.classList.remove('show');
    myLable20.classList.remove('label-colour');
};

myLable18.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio18);
    myNounMusic.textContent = 'instagramda en çok aranan rusça şarkı';
    myAudio1.classList.remove('show');
    myAudio1.classList.add('hidden');
    myLable1.classList.remove('label-colour');
    myAudio2.classList.add('hidden');
    myAudio2.classList.remove('show');
    myAudio2.classList.add('hidden');
    myLable2.classList.remove('label-colour');
    myAudio3.classList.remove('show');
    myLable3.classList.remove('label-colour');
    myAudio4.classList.add('hidden');
    myAudio4.classList.remove('show');
    myLable4.classList.remove('label-colour');
    myAudio5.classList.add('hiiden');
    myAudio5.classList.remove('show');
    myLable5.classList.remove('label-colour');
    myAudio6.classList.add('hidden');
    myAudio6.classList.remove('show');
    myLable6.classList.remove('label-colour');
    myAudio7.classList.add('hidden');
    myAudio7.classList.remove('show');
    myLable7.classList.remove('label-colour');
    myAudio8.classList.add('hidden');
    myAudio8.classList.remove('show');
    myLable8.classList.remove('label-colour');
    myAudio9.classList.add('hidden');
    myAudio9.classList.remove('show');
    myLable9.classList.remove('label-colour');
    myAudio10.classList.add('hidden');
    myAudio10.classList.remove('show');
    myLable10.classList.remove('label-colour');
    myAudio11.classList.add('hidden');
    myAudio11.classList.remove('show');
    myLable11.classList.remove('label-colour');
    myAudio12.classList.add('hidden');
    myAudio12.classList.remove('show');
    myLable12.classList.remove('label-colour');
    myAudio13.classList.add('hidden');
    myAudio13.classList.remove('show');
    myLable13.classList.remove('label-colour');
    myAudio14.classList.add('hidden');
    myAudio14.classList.remove('show');
    myLable14.classList.remove('label-colour');
    myAudio15.classList.add('hidden');
    myAudio15.classList.remove('show');
    myLable15.classList.remove('label-colour');
    myAudio16.classList.add('hidden');
    myAudio16.classList.remove('show');
    myLable16.classList.remove('label-colour');
    myAudio17.classList.add('hidden');
    myAudio17.classList.remove('show');
    myLable17.classList.remove('label-colour');
    myAudio18.classList.add('show');
    myAudio18.classList.remove('hidden');
    myLable18.classList.add('label-colour');
    myAudio19.classList.add('hidden');
    myAudio19.classList.remove('show');
    myLable19.classList.remove('label-colour');
    myAudio20.classList.add('hidden');
    myAudio20.classList.remove('show');
    myLable20.classList.remove('label-colour');
};

myLable19.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio19);
    myNounMusic.textContent = 'Katy Perry - Never Really Over';
    myAudio1.classList.remove('show');
    myAudio1.classList.add('hidden');
    myLable1.classList.remove('label-colour');
    myAudio2.classList.add('hidden');
    myAudio2.classList.remove('show');
    myAudio2.classList.add('hidden');
    myLable2.classList.remove('label-colour');
    myAudio3.classList.remove('show');
    myLable3.classList.remove('label-colour');
    myAudio4.classList.add('hidden');
    myAudio4.classList.remove('show');
    myLable4.classList.remove('label-colour');
    myAudio5.classList.add('hiiden');
    myAudio5.classList.remove('show');
    myLable5.classList.remove('label-colour');
    myAudio6.classList.add('hidden');
    myAudio6.classList.remove('show');
    myLable6.classList.remove('label-colour');
    myAudio7.classList.add('hidden');
    myAudio7.classList.remove('show');
    myLable7.classList.remove('label-colour');
    myAudio8.classList.add('hidden');
    myAudio8.classList.remove('show');
    myLable8.classList.remove('label-colour');
    myAudio9.classList.add('hidden');
    myAudio9.classList.remove('show');
    myLable9.classList.remove('label-colour');
    myAudio10.classList.add('hidden');
    myAudio10.classList.remove('show');
    myLable10.classList.remove('label-colour');
    myAudio11.classList.add('hidden');
    myAudio11.classList.remove('show');
    myLable11.classList.remove('label-colour');
    myAudio12.classList.add('hidden');
    myAudio12.classList.remove('show');
    myLable12.classList.remove('label-colour');
    myAudio13.classList.add('hidden');
    myAudio13.classList.remove('show');
    myLable13.classList.remove('label-colour');
    myAudio14.classList.add('hidden');
    myAudio14.classList.remove('show');
    myLable14.classList.remove('label-colour');
    myAudio15.classList.add('hidden');
    myAudio15.classList.remove('show');
    myLable15.classList.remove('label-colour');
    myAudio16.classList.add('hidden');
    myAudio16.classList.remove('show');
    myLable16.classList.remove('label-colour');
    myAudio17.classList.add('hidden');
    myAudio17.classList.remove('show');
    myLable17.classList.remove('label-colour');
    myAudio18.classList.add('hidden');
    myAudio18.classList.remove('show');
    myLable18.classList.remove('label-colour');
    myAudio19.classList.add('show');
    myAudio19.classList.remove('hidden');
    myLable19.classList.add('label-colour');
    myAudio20.classList.add('hidden');
    myAudio20.classList.remove('show');
    myLable20.classList.remove('label-colour');
};

myLable20.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio20);
    myNounMusic.textContent = 'Lil Nas X - Old Town Road';
    myAudio1.classList.remove('show');
    myAudio1.classList.add('hidden');
    myLable1.classList.remove('label-colour');
    myAudio2.classList.add('hidden');
    myAudio2.classList.remove('show');
    myAudio2.classList.add('hidden');
    myLable2.classList.remove('label-colour');
    myAudio3.classList.remove('show');
    myLable3.classList.remove('label-colour');
    myAudio4.classList.add('hidden');
    myAudio4.classList.remove('show');
    myLable4.classList.remove('label-colour');
    myAudio5.classList.add('hiiden');
    myAudio5.classList.remove('show');
    myLable5.classList.remove('label-colour');
    myAudio6.classList.add('hidden');
    myAudio6.classList.remove('show');
    myLable6.classList.remove('label-colour');
    myAudio7.classList.add('hidden');
    myAudio7.classList.remove('show');
    myLable7.classList.remove('label-colour');
    myAudio8.classList.add('hidden');
    myAudio8.classList.remove('show');
    myLable8.classList.remove('label-colour');
    myAudio9.classList.add('hidden');
    myAudio9.classList.remove('show');
    myLable9.classList.remove('label-colour');
    myAudio10.classList.add('hidden');
    myAudio10.classList.remove('show');
    myLable10.classList.remove('label-colour');
    myAudio11.classList.add('hidden');
    myAudio11.classList.remove('show');
    myLable11.classList.remove('label-colour');
    myAudio12.classList.add('hidden');
    myAudio12.classList.remove('show');
    myLable12.classList.remove('label-colour');
    myAudio13.classList.add('hidden');
    myAudio13.classList.remove('show');
    myLable13.classList.remove('label-colour');
    myAudio14.classList.add('hidden');
    myAudio14.classList.remove('show');
    myLable14.classList.remove('label-colour');
    myAudio15.classList.add('hidden');
    myAudio15.classList.remove('show');
    myLable15.classList.remove('label-colour');
    myAudio16.classList.add('hidden');
    myAudio16.classList.remove('show');
    myLable16.classList.remove('label-colour');
    myAudio17.classList.add('hidden');
    myAudio17.classList.remove('show');
    myLable17.classList.remove('label-colour');
    myAudio18.classList.add('hidden');
    myAudio18.classList.remove('show');
    myLable18.classList.remove('label-colour');
    myAudio19.classList.add('hidden');
    myAudio19.classList.remove('hidden');
    myLable19.classList.remove('label-colour');
    myAudio20.classList.add('hidden');
    myAudio20.classList.remove('show');
    myLable20.classList.add('label-colour');
};

myLable21.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio21);
    myNounMusic.textContent = 'Lost Frequencies _ Netsky - Here With You';
};

myLable22.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio22);
    myNounMusic.textContent = 'Lil Dicky - Earth';
};

myLable23.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio23);
    myNounMusic.textContent = 'Justin Bieber _ BloodPop® - Friends';
};

myLable24.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio24);
    myNounMusic.textContent = 'Justin Bieber - Love Yourself ';
};

myLable25.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio25);
    myNounMusic.textContent = 'Justin Bieber - I_ll Show You';
};

myLable26.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio26);
    myNounMusic.textContent = 'Justin Bieber - Company';
};

myLable27.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio27);
    myNounMusic.textContent = 'Joyner Lucas ft. Logic - ISIS';
};

myLable28.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio28);
    myNounMusic.textContent = 'BGone in the Sun - Coming Alive';
};

myLable29.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio29);
    myNounMusic.textContent = 'Luis Fonsi_ Demi Lovato - Échame La Culpa';
};

myLable30.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio30);
    myNounMusic.textContent = 'ON AN ON - Drifting';
};

myLable31.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio31);
    myNounMusic.textContent = 'OneRepublic - Let_s Hurt Tonight';
};

myLable32.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio32);
    myNounMusic.textContent = 'Maluma - HP';
};

myLable33.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio33);
    myNounMusic.textContent = 'Halsey - Nightmare';
};

myLable34.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio34);
    myNounMusic.textContent = 'Macklemore - Can_t hold us';
};

myLable35.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio35);
    myNounMusic.textContent = 'Khalid - Talk';
};

myLable36.onclick = function () {
    'use strict';
    myLables.classList.add('hidden');
    myLables.classList.remove('show');
    myAudioSpace.classList.add('show');
    myAudioSpace.classList.remove('hidden');
    myAudio.appendChild(myAudio36);
    myNounMusic.textContent = 'Konoba - On Our Knees';
};



myBackLis.onclick = function () {
    'use strict';
    myLables.classList.add('show');
    myAudioSpace.classList.add('hidden');
    myAudioSpace.classList.remove('show');
    myLables.classList.remove('hidden');
};
